workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
      when: always
    - when: never

variables:
  DOCKER_BUILDKIT: "0"
  MONO_REPO: "api"                            #Change_Me  (gitlab project name => api or ui)
  MICRO_SERVICE: "bale_scraper-api"            #Change_Me  (deployment name & argocd application name) => project-api or project-ui
  YAMLS_REPO: "k8s-yaml"
  SECRET_NAME: "services"
  REPOSITORY_YAML: "git@gitlab.local:kandoo/bale-scraper/backend/k8s-yaml.git"          #Change_Me  (k8s-yaml project's ssh url)
  REPOSITORY_SSH_URL: "git@${CI_SERVER_HOST}:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"

stages:
  - build_update_manifest
  - push_manifest
  - argo_refresh
  - merge_to_production           #Change_Me_Production  (comment this line)

.build:
  stage: build_update_manifest
  tags:
    - runner1                     #Change_Me_Production  (change to runner1)
  variables:
    CONTAINER_PORT: "8000"        #Change_Me  (service port : 80 or 8000)
    REPLICAS: ""
    STAGE_NAME: ""
    DOCKERFILE_NAME: ""
  before_script:
  #  - cd project_directory       #Change_Me  (if exist folder for code files)
    - export APP_VERSION=$(cat version.txt)
    - export RANDOM_HASH=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 10)
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/microservice/$MICRO_SERVICE-$STAGE_NAME
    - export IMAGE_TAG=$APP_VERSION-$RANDOM_HASH
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f $DOCKERFILE_NAME .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - envsubst < kubernetes/deployment.yaml > deployment-$MICRO_SERVICE.yaml
  artifacts:
    paths:
      - deployment-$MICRO_SERVICE.yaml
    expire_in: 1 hour

    ##################################### build_update_manifest #####################################

build-production:
  extends: .build
  variables:
    REPLICAS: "1"
    STAGE_NAME: "production"
    DOCKERFILE_NAME: "Dockerfile"   #Change_Me  (if exist Dockerfile.prod)
  only:
    - production

build-staging:
  extends: .build
  variables:
    REPLICAS: "1"
    STAGE_NAME: "staging"
    DOCKERFILE_NAME: "Dockerfile"   #Change_Me  (if exist Dockerfile.stage)
  only:
    - main

######################################## push manifest ##########################################

.push:
  stage: push_manifest
  tags:
    - runner1                      #Change_Me_Production  (change to runner1)
  variables:
    BRANCH: ""
  script:
    - cd ..
    - rm -rf $YAMLS_REPO
    - git clone -b $BRANCH $REPOSITORY_YAML
    - cd $YAMLS_REPO
    - mv -t . ../$MONO_REPO/deployment*
    - git config --global user.email "runner@gmail.com"
    - git config --global user.name "shell-runner"
    - git add .
    - git commit -m "update yaml files"
    - git push
    - cd ..
    - rm -rf $YAMLS_REPO

push-production:
  extends: .push
  variables:
    BRANCH: "main"                 #Change_Me  ("main" or "master" for k8s-yaml)
  only:
    - production

push-staging:
  extends: .push
  variables:
    BRANCH: "staging"
  only:
    - main

########################################## refresh argocd ##########################################

.refresh:
  stage: argo_refresh
  tags:
    - runner1                     #Change_Me_Production  (change to runner1)
  script:
    - argocd login $argohost --insecure --username $argouser --password $argopass   #Change_Me_Production  (Ex: argohost_stg => argohost)
    - argocd  app get $MICRO_SERVICE --refresh
    - sleep 10
    - echo "your application deploy it successfully."

argo-refresh-production:
  extends: .refresh
  only:
    - production

argo-refresh-staging:
  extends: .refresh
  only:
    - main

########################################## merge to main ##########################################

.merge:                            #Change_Me_Production  (comment completely this stage)
  stage: merge_to_production
  tags:
    - runner1
  variables:
    TARGET_BRANCH: ""
  script:
    # Configure Git
    - git config --global user.email "runner@gmail.com"
    - git config --global user.name "shell-runner"
    - git fetch origin
    # Set the Git remote URL to use SSH for secure operations
    - git remote set-url origin $REPOSITORY_SSH_URL
    # Checkout the target branch to prepare for syncing
    - git checkout $TARGET_BRANCH
    # Reset the branch to the current commit from the source branch
    - git reset --hard $CI_COMMIT_SHA
    # Restore specific files that should not be overwritten (e.g., CI pipeline config)
    - git restore --source=origin/$TARGET_BRANCH -- .gitlab-ci.yml                     #Change_Me  (write different files between staging and production, like .gitlab-ci.yml)
    # Push changes to the target branch, forcing updates
    - git add .
    - git commit -m "Sync to $CI_COMMIT_REF_NAME commit = $CI_COMMIT_SHA"
    - git pull
    # Push changes to the target branch, forcing updates
    - git push origin $TARGET_BRANCH --force

merge-to-production:
  extends: .merge
  variables:
    TARGET_BRANCH: "production"
  when: manual
  dependencies: []
  only:
    - main
